tap "getsentry/tools"
tap "homebrew/bundle"
brew "bash"
brew "bash-completion"
brew "git"
brew "nmap"
brew "rake-completion"
brew "ruby-build"
brew "rbenv"
brew "swift-outdated"
brew "wget"
brew "xcodes", link: false
brew "getsentry/tools/sentry-cli"
cask "1password-cli"
cask "mactex-no-gui"
cask "mockoon"
cask "xcodes"
